### ISSUE TITLE
ReferenceError: sql is not defined

### ISSUE THREAD

**Issue by gregorwolf** [just-bi/odxl#28]
After an upgrade to HANA 1.00.122.02.1473345179 our users faced the issue that when they clicked the export to excel the error:

`ReferenceError: sql is not defined`

occured. I've debugged and found that the root cause was in the function buildQueryFromClause of querybuilder.xsjslib. There sql.checkIdentifier is called but as the variable sql seems not to be defined the error is raised.

**Comment by rpbouman** [comment]
Thanks!
